### ISSUE TITLE
Find a good strategy to deal with decorated components

### ISSUE THREAD

**Issue by nikgraf** [pure-ui/styleguide#125]
I encountered the issue while trying to fix the JSS example. 

```
ERROR in ./plugin/meta-loader.js!./examples/jss/src/components/Profile/index.js
    Module build failed: Error: No suitable component definition found.
        at parse (/some/path/node_modules/react-docgen/dist/parse.js:80:9)
        at Object.defaultParse [as parse] (/some/path/node_modules/react-docgen/dist/main.js:65:33)
```

One strategy could be that `useSheet` also exposes the propTypes, but then I guess it still won't work with FlowTypes. Any ideas? /cc @kof

**Comment by nikgraf** [comment]
Hmmm @mxstbr just made a good point. react-docgen parses the source and does a AST analysis. It might be possible to improve react-docgen in that case.
